#!/bin/bash
set -vx
declare -A labels
declare -a networks ipv4_addresses
docker ps -f label=networks --format '{{.ID}}\t{{.Labels}}' | while read id labels; do
	eval labels=($(sed -E -e 's/([-_.[:alnum:]]+)=/[\1]\="/g;s/,/" /g;s/$/"/'<<<"$labels"))
	eval networks=($(sed -e 's/,/ /g'<<<${labels[networks]//,/ }))
	eval ipv4_addresses=($(sed -e 's/,/ /g'<<<${labels[ipv4_addresses]//,/ }))
	for ((i=${#networks[@]}; --i>=0; )); do
		ip=${ipv4_addresses[$i]}
		docker network connect "${networks[$i]}" ${ip:+--ip=$ip} "$id"
	done
done
