---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: kafka-manager
  namespace: kafka
  name: cmak
spec:
  virtualhost:
    fqdn: cmak.kafka
  routes:
  - services:
    - name: cmak-kafka-manager
      port: 9000
