---
apiVersion: v1
kind: Service
metadata:
  labels:
    release: kafka
    app: cp-kafka
  namespace: kafka
  name: kafka-cp-kafka-0
spec:
  type: LoadBalancer
  loadBalancerIP: 172.23.150.230
  ports:
  - name: kafka-plaintext
    port: 9092
    targetPort: 9092
  selector:
    statefulset.kubernetes.io/pod-name: kafka-cp-kafka-0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    release: kafka
    app: cp-kafka
  namespace: kafka
  name: kafka-cp-kafka-1
spec:
  type: LoadBalancer
  loadBalancerIP: 172.23.150.231
  ports:
  - name: kafka-plaintext
    port: 9092
    targetPort: 9092
  selector:
    statefulset.kubernetes.io/pod-name: kafka-cp-kafka-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    release: kafka
    app: cp-kafka
  namespace: kafka
  name: kafka-cp-kafka-2
spec:
  type: LoadBalancer
  loadBalancerIP: 172.23.150.232
  ports:
  - name: kafka-plaintext
    port: 9092
    targetPort: 9092
  selector:
    statefulset.kubernetes.io/pod-name: kafka-cp-kafka-2
