---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-0
  namespace: kafka
  name: kafka-0
spec:
  type: LoadBalancer
  loadBalancerIP: 172.30.255.240
  ports:
  - name: kafka-plaintext
    port: 9092
    targetPort: 9092
  - name: kafka-sasl-plaintext
    port: 9093
    targetPort: 9093
  selector:
    statefulset.kubernetes.io/pod-name: kafka-cp-kafka-0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-1
  namespace: kafka
  name: kafka-1
spec:
  type: LoadBalancer
  loadBalancerIP: 172.30.255.241
  ports:
  - name: kafka-plaintext
    port: 9092
    targetPort: 9092
  - name: kafka-sasl-plaintext
    port: 9093
    targetPort: 9093
  selector:
    statefulset.kubernetes.io/pod-name: kafka-cp-kafka-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-2
  namespace: kafka
  name: kafka-2
spec:
  type: LoadBalancer
  loadBalancerIP: 172.30.255.242
  ports:
  - name: kafka-plaintext
    port: 9092
    targetPort: 9092
  - name: kafka-sasl-plaintext
    port: 9093
    targetPort: 9093
  selector:
    statefulset.kubernetes.io/pod-name: kafka-cp-kafka-2
