---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    release: kafka
    app: cp-kafka-rest
  namespace: kafka
  name: kafka-rest-route
spec:
  routes:
  - services:
    - name: kafka-cp-kafka-rest
      port: 8082
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    release: kafka
    app: cp-kafka-rest
  namespace: kafka
  name: kafka-cp-kafka-rest
spec:
  virtualhost:
    fqdn: kafka-cp-kafka-rest.kafka
  includes:
  - name: kafka-rest-route
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    release: kafka
    app: cp-kafka-rest
  namespace: kafka
  name: kafka-rest
spec:
  virtualhost:
    fqdn: kafka-rest.kafka
  includes:
  - name: kafka-rest-route
