---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    release: kafka
    app: cp-schema-registry
  namespace: kafka
  name: schema-registry-route
spec:
  routes:
  - services:
    - name: kafka-cp-schema-registry
      port: 8081
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    release: kafka
    app: cp-schema-registry
  namespace: kafka
  name: kafka-cp-schema-registry
spec:
  virtualhost:
    fqdn: kafka-cp-schema-registry.kafka
  includes:
  - name: schema-registry-route
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    release: kafka
    app: cp-schema-registry
  namespace: kafka
  name: schema
spec:
  virtualhost:
    fqdn: schema.kafka
  includes:
  - name: schema-registry-route
