---
apiVersion: v1
kind: Service
metadata:
  labels:
    release: kafka
    app: cp-zookeeper
  namespace: kafka
  name: kafka-cp-zookeeper-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 172.23.150.233
  ports:
  - name: zookeeper-port
    port: 2181
    targetPort: 2181
  selector:
    release: kafka
    app: cp-zookeeper
