---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  namespace: kafka
  name: zookeeper-service
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.255.249
  ports:
  - name: zookeeper-port
    port: 2181
    targetPort: 2181
  selector:
    app: cp-zookeeper
    release: kafka
